// DiskAnalyzer — Electron main process.
// Per 07-ELECTRON-APP-SHELL.md §7.1 + §7.2.
//
// Phase 4 additions: LicenseClient + capability gating at Layer B.

import { existsSync, mkdirSync, readFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { BrowserWindow, app, ipcMain, shell } from 'electron';

import { LicenseClient, type LicenseStatus } from '@disk-analyzer/license-client';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

let rustCore: any | null = null;
let mockMode = false;

try {
  rustCore = await import('@disk-analyzer/napi');
  console.log('[spatium] Rust core loaded; version:', rustCore.engineVersion?.() ?? 'unknown');
} catch (err) {
  console.warn('[spatium] Rust core not available; using Mock IPC mode.', err);
  mockMode = true;
}

// ─────────────────────────────────────────────────────────────────────
// LicenseClient
// ─────────────────────────────────────────────────────────────────────

// Find the dev public key (generated by the licensing server on first run).
// In production, this would be the prod.public.der baked into the app at build time.
const DEV_PUB_KEY_PATH = join(
  __dirname,
  '..',
  '..',
  '..',
  'apps',
  'licensing-server',
  'src',
  'keys',
  'dev.public.der',
);
let publicKeyDer: Buffer | null = null;
if (existsSync(DEV_PUB_KEY_PATH)) {
  publicKeyDer = readFileSync(DEV_PUB_KEY_PATH);
} else {
  // Fall back to a placeholder key. The client will reject all entitlements
  // until the licensing server is started (which generates the real keypair).
  publicKeyDer = Buffer.alloc(32, 0);
  console.warn('[spatium] Dev public key not found at', DEV_PUB_KEY_PATH);
  console.warn('[spatium] Start the licensing server first: cd apps/licensing-server && pnpm dev');
}

const licenseStorageDir = join(homedir(), '.spatium', 'license');
mkdirSync(licenseStorageDir, { recursive: true });
const licenseStoragePath = join(licenseStorageDir, 'entitlement.bin');

// Install salt — persisted per installation. For Phase 4 dev, we use the
// process.env.SPATIUM_INSTALL_SALT if set, else a fixed dev salt.
const installSalt = process.env.SPATIUM_INSTALL_SALT ?? 'spatium-dev-install-salt';

const licenseClient = new LicenseClient({
  endpoint: process.env.SPATIUM_LICENSE_ENDPOINT ?? 'http://127.0.0.1:8080',
  publicKeyDer: publicKeyDer!,
  storagePath: licenseStoragePath,
  installSalt,
});

// Forward license status changes to the renderer.
let licenseStatus: LicenseStatus = { kind: 'free' };
licenseClient.on('statusChanged', (s: LicenseStatus) => {
  licenseStatus = s;
  for (const win of BrowserWindow.getAllWindows()) {
    if (!win.isDestroyed()) {
      win.webContents.send('license:statusChanged', s);
    }
  }
});

// ─────────────────────────────────────────────────────────────────────
// Window
// ─────────────────────────────────────────────────────────────────────

const isDev = !app.isPackaged;

function createWindow(): BrowserWindow {
  const win = new BrowserWindow({
    width: 1440,
    height: 900,
    minWidth: 1024,
    minHeight: 700,
    show: false,
    backgroundColor: '#0F1115',
    titleBarStyle: 'hidden',
    titleBarOverlay: {
      color: '#161A21',
      symbolColor: '#E6E9EF',
      height: 36,
    },
    ...(process.platform === 'win32' ? { backgroundMaterial: 'mica' as const } : {}),
    ...(process.platform === 'darwin' ? { vibrancy: 'under-window' as const } : {}),
    webPreferences: {
      preload: join(__dirname, '../preload/index.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
      webSecurity: true,
      allowRunningInsecureContent: false,
      experimentalFeatures: false,
      spellcheck: false,
    },
  });

  win.once('ready-to-show', () => win.show());

  if (isDev) {
    void win.loadURL('http://localhost:5173');
    win.webContents.openDevTools({ mode: 'detach' });
  } else {
    void win.loadFile(join(__dirname, '../renderer/index.html'));
  }

  return win;
}

// ─────────────────────────────────────────────────────────────────────
// Single-instance lock
// ─────────────────────────────────────────────────────────────────────

const gotLock = app.requestSingleInstanceLock();
if (!gotLock) {
  app.quit();
} else {
  app.on('second-instance', () => {
    const wins = BrowserWindow.getAllWindows();
    if (wins.length > 0) {
      const win = wins[0]!;
      if (win.isMinimized()) win.restore();
      win.focus();
    }
  });
}

// ─────────────────────────────────────────────────────────────────────
// Capability gating at Layer B (NOT in the renderer).
// Per 14-LICENSING-CLIENT.md §14.7 + 15-SECURITY-ARCHITECTURE.md §15.4.
// ─────────────────────────────────────────────────────────────────────

function capabilityAllows(feature: string): boolean {
  if (mockMode) {
    // Mock IPC mode: allow everything (for dev without license server).
    return true;
  }
  return licenseClient.entitlementAllows(feature);
}

// ─────────────────────────────────────────────────────────────────────
// IPC handlers
// ─────────────────────────────────────────────────────────────────────

ipcMain.handle('app:getVersion', () => app.getVersion());
ipcMain.handle('app:getPlatform', () => process.platform);
ipcMain.handle('app:openExternal', (_event, url: string) => {
  try {
    const parsed = new URL(url);
    if (parsed.protocol === 'http:' || parsed.protocol === 'https:') {
      return shell.openExternal(url);
    }
  } catch {
    // Invalid URL; ignore.
  }
  return undefined;
});

ipcMain.handle('scan:start', async (_event, req: unknown) => {
  // Capability check at Layer B (per §14.7).
  // Free tier is allowed to scan; only Pro features (duplicate, usn, etc.) are gated.
  const opts =
    (req as { options: { hashDuplicates?: boolean; incrementalUsn?: boolean } }).options ?? {};
  if (opts.hashDuplicates && !capabilityAllows('duplicate.analysis')) {
    return { ok: false, error: 'LICENSE_REQUIRED' };
  }
  if (opts.incrementalUsn && !capabilityAllows('historical.scans')) {
    return { ok: false, error: 'LICENSE_REQUIRED' };
  }

  if (mockMode || rustCore === null) {
    console.log('[mock] scan:start', req);
    return { ok: true, scanId: 'mock-scan-1' };
  }
  const { root, options } = req as { root: string; options: any };
  try {
    const scanId = rustCore.scanStart(root, options, undefined);
    return { ok: true, scanId };
  } catch (err) {
    return { ok: false, error: 'UNKNOWN_ERROR', message: String(err) };
  }
});

ipcMain.handle('scan:cancel', async () => {
  if (mockMode || rustCore === null) {
    return true;
  }
  return rustCore.scanCancel();
});

ipcMain.handle('scan:status', async (_event, _scanId: string) => {
  if (mockMode || rustCore === null) {
    return null;
  }
  return rustCore.getScanStatus();
});

// ─── License IPC handlers ─────────────────────────────────────────

ipcMain.handle('license:activate', async (_event, key: string) => {
  const result = await licenseClient.activate(key);
  return result;
});

ipcMain.handle('license:deactivate', async () => {
  await licenseClient.deactivate();
});

ipcMain.handle('license:status', async () => {
  return licenseClient.getStatus();
});

// Forward scan events from the Rust core to the renderer.
function registerScanEventForwarder(win: BrowserWindow) {
  if (mockMode || rustCore === null) return;
  rustCore.onScanEvent((event: any) => {
    if (!win.isDestroyed()) {
      win.webContents.send('scan:batch', event);
    }
  });
}

// ─────────────────────────────────────────────────────────────────────
// App lifecycle
// ─────────────────────────────────────────────────────────────────────

app.whenReady().then(async () => {
  await licenseClient.init();
  const win = createWindow();
  registerScanEventForwarder(win);
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

app.on('before-quit', async () => {
  await licenseClient.dispose();
});
