/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS (committed for CI typecheck; safe to overwrite with `napi build --dts`). */

/** Event payload delivered to the JS callback. Mirrors `ScanEvent` in `packages/ipc/src/types.ts`. */
export interface ScanEventDto {
  scanId: string
  parentId: number
  name: string
  logical: bigint
  allocated: bigint
  mtime: number
  ctime: number
  attrs: number
  reparseKind: string
  hardlinkCount: number
  sparse: boolean
  fileId: bigint
}
/** Scan options. Passed from JS; we parse strings to enums inside Rust. */
export interface ScanOptionsDto {
  followReparsePoints: string
  countHardLinks: string
  hashDuplicates: boolean
  respectGitignore: boolean
  includePatterns: Array<string>
  excludePatterns: Array<string>
  minSizeBytes?: bigint
  maxDepth?: number
  incrementalUsn: boolean
  priorScanId?: string
}
/** Scan status snapshot. */
export interface ScanStatusDto {
  scanId: string
  phase: string
  elapsedMs: bigint
  filesScanned: bigint
  bytesScanned: bigint
  bytesAllocated: bigint
  currentPath?: string
  error?: string
}
/** Progress DTO mirroring the TS `ScanProgressEvent`. */
export interface ScanProgressDto {
  scanId: string
  phase: string
  filesScanned: bigint
  bytesScanned: bigint
  bytesAllocated: bigint
  elapsedMs: bigint
}
/**
 * Register a callback for scan events. The callback is invoked from the worker
 * thread for each coalesced batch. Per `08-RENDERER-REACT-APP.md` §8.14, the
 * renderer subscribes via the preload's `diskanalyzer.scan.onBatch(cb)`.
 */
export declare function onScanEvent(callback: (err: Error | null, arg: ScanEventDto) => any): void
/** Start a scan. Returns the scan ID (string) on success. */
export declare function scanStart(root: string, options: ScanOptionsDto, progressCallback?: (err: Error | null, arg: ScanProgressDto) => any | undefined | null): string
/** Cancel the active scan. Returns true if a scan was active. */
export declare function scanCancel(): boolean
/** Get the active scan ID (string) or null. */
export declare function getActiveScanId(): string | null
/** Get the status snapshot of the active scan (or null). */
export declare function getScanStatus(): ScanStatusDto | null
/** Engine version (per `05-RUST-CORE-ENGINE.md` §5.14). */
export declare function engineVersion(): string
